/**
 * @File Name          : Test.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 13/8/2019, 9:20:23 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    13/8/2019, 9:19:30 PM   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class Test{

    public void test1(){
        System.debug('hello1');
    }
}